name: Tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-ss
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4
      id: go

    - name: Check out source
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install libgit2
      run: make libgit2

    - name: Vet
      run: make vet

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0
        make lint-ci
    
    - name: Test
      run: make test-cover
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3

  # TODO(patrickdevivo)
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install libgit2
  #       run: |
  #         git clone https://github.com/libgit2/libgit2.git ~/libgit2
  #         cd ~/libgit2
  #         git checkout v1.1.0
  #         mkdir build && cd build
  #         sudo cmake .. -DBUILD_CLAR=0
  #         sudo cmake --build . --target install

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.29
  #         args: --build-tags sqlite_vtable,static,system_libgit2
